relative_url/fun_app/urls.py
from django.contrib import admin
from django.urls import path
from fun_app import views

app_name = 'fun_app'

urlpatterns = [
    path('',views.index,name='index'),
    path('relative/', views.relative,name='relative'),
    path('other/', views.other,name='other'),
]

relative_url/relative_url/urls.py
from django.contrib import admin
from django.urls import path, include
from fun_app import views

urlpatterns = [
    path('fun_app/',include("fun_app.urls")),
    path('admin/', admin.site.urls),
]

relative_url/fun_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request,'fun_app/index.html')

def relative(request):
    return render(request,'fun_app/relative.html')

def other(request):
    return render(request,'fun_app/other.html')

relative_url/templates/fun_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="navbar-brand">Testing</a></li>
          <li class="navbar-link" ><a href="{% url 'fun_app:index' %}">Index</a></li>
          <li class="navbar-link" ><a href="{% url 'fun_app:relative' %}">Relative</a></li>
          <li class="navbar-link"><a href="{% url 'fun_app:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>
    {% block body_block %}

    {% endblock %}

  </body>

</html>

relative_url/templates/fun_app/index.html
<!DOCTYPE html>
{% extends "fun_app/base.html" %}
{% block body_block %}
  <h1>Welcome to index page</h1>
{% endblock %}

relative_url/templates/fun_app/other.html
<!DOCTYPE html>
{% extends "fun_app/base.html" %}
{% block body_block %}
  <h1>Welcome to Other page</h1>
{% endblock %}

relative_url/templates/fun_app/relative.html
<!DOCTYPE html>
{% extends "fun_app/base.html" %}
{% block body_block %}
  <h1>Welcome to Relative page</h1>
{% endblock %}