authentication/authentication/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

authentication/basic_app/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

app_name='basic_app'

urlpatterns = [
    path('register/',views.register,name='register'),
]

authentication/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to="profile_pic", blank=True)

authentication/basic_app/forms.py
from basic_app import UserInfo
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        field = ('username','email','password')

class UserInfoForm(forms.ModelForm):

    class Meta():
        model = UserInfo
        field = ('profile_pic','portfolio')

authentication/basic_app/views.py
from django.shortcuts import render

# Create your views here.

authentication/authentication/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="nav navbar-default navbar-static-top">
      <div class="contained">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}"></a>Django Index</li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}"></a>Admin</li>
          <li><a class="navbar-link" href="{% url 'basic_app:register' %}"></a>Register</li>

        </ul>

      </div>

    </nav>

    {% block body_block %}
    {% endblock %}

  </body>
  <!-- Latest compiled and minified JavaScript -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

authentication/authentication/templates/basic_app/index.html
{%extends "basic_app/base.html"%}
{% block body_block %}

<div class="jumbotron">
  <h1>Lvel 5</h1>

</div>

{% endblock %}

authentication/authentication/templates/basic_app/login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

  </body>
</html>

authentication/authentication/templates/basic_app/registration.html
{%extends "basic_app/base.html"%}
{%load staticfiles %}
{% block body_block %}

<div class="jumbotron">
  {% if registered %}
  <h1> Thanks for registering </h1>
  {% else %}
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="" value="register">
  </form>
  {% endif%}
</div>

{% endblock %}